{
  "Header": {
    "Original": "CVE-2019-13057 (An issue was discovered in the server in OpenLDAP before 2.4.48. When  ...)",
    "ID": "CVE-2019-13057",
    "Description": "(An issue was discovered in the server in OpenLDAP before 2.4.48. When  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1891-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-1891-1"
      ]
    },
    {
      "Original": "- openldap 2.4.48+dfsg-1 (low; bug #932997)",
      "Type": "package",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.48+dfsg-1",
      "Severity": "low",
      "BugNo": 932997
    },
    {
      "Original": "[buster] - openldap 2.4.47+dfsg-3+deb10u1",
      "Type": "package",
      "Release": "buster",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.47+dfsg-3+deb10u1"
    },
    {
      "Original": "[stretch] - openldap 2.4.44+dfsg-5+deb9u3",
      "Type": "package",
      "Release": "stretch",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.44+dfsg-5+deb9u3"
    },
    {
      "Original": "NOTE: https://openldap.org/its/?findid=9038",
      "Type": "NOTE",
      "Description": "https://openldap.org/its/?findid=9038"
    }
  ]
}