{
  "Header": {
    "Original": "CVE-2022-22844 (LibTIFF 4.3.0 has an out-of-bounds read in _TIFFmemcpy in tif_unix.c i ...)",
    "ID": "CVE-2022-22844",
    "Description": "(LibTIFF 4.3.0 has an out-of-bounds read in _TIFFmemcpy in tif_unix.c i ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5108-1 DLA-2932-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5108-1",
        "DLA-2932-1"
      ]
    },
    {
      "Original": "- tiff 4.3.0-3",
      "Type": "package",
      "Package": "tiff",
      "Kind": "fixed",
      "Version": "4.3.0-3"
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/issues/355",
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/issues/355"
    },
    {
      "Original": "NOTE: https://gitlab.com/libtiff/libtiff/-/merge_requests/287",
      "Type": "NOTE",
      "Description": "https://gitlab.com/libtiff/libtiff/-/merge_requests/287"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.com/libtiff/libtiff/-/commit/03047a26952a82daaa0792957ce211e0aa51bc64",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.com/libtiff/libtiff/-/commit/03047a26952a82daaa0792957ce211e0aa51bc64"
    }
  ]
}