{
  "Header": {
    "Original": "CVE-2021-41496 (Buffer overflow in the array_from_pyobj function of fortranobject.c in ...)",
    "ID": "CVE-2021-41496",
    "Description": "(Buffer overflow in the array_from_pyobj function of fortranobject.c in ...)"
  },
  "Annotations": [
    {
      "Original": "- numpy \u003cunfixed\u003e (unimportant)",
      "Type": "package",
      "Package": "numpy",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/issues/19000",
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/issues/19000"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/pull/20630",
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/pull/20630"
    },
    {
      "Original": "NOTE: https://github.com/numpy/numpy/commit/271010f1037150e95017f803f4214b8861e528f2",
      "Type": "NOTE",
      "Description": "https://github.com/numpy/numpy/commit/271010f1037150e95017f803f4214b8861e528f2"
    }
  ]
}